name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: arc-runner-set

    steps:
      - name: Print a message
        run: echo "Hello, GitHub Actions!! ASDF"
